from pathlib import Path
import re,json,html,shutil,hashlib
src=Path('content'); out=Path('.'); (out/'research').mkdir(exist_ok=True)
esc=html.escape
pubs=json.loads(Path('publications.json').read_text())
base=(src/'index.html').read_text()

def extract(s,tag,cls):
 return re.search(r'<'+tag+r'[^>]*class="'+cls+r'"[^>]*>.*?</'+tag+r'>',s,re.S).group()
def shell(title,body,depth='',active=''):
 page_title=f'{title} | Raoof Zare Moayedi' if title else 'Raoof Zare Moayedi'
 style_version=hashlib.sha256((out/'assets/redesign.css').read_bytes()).hexdigest()[:12]
 script_version=hashlib.sha256((out/'assets/site.js').read_bytes()).hexdigest()[:12]
 mark_version=hashlib.sha256((out/'assets/monogram.svg').read_bytes()).hexdigest()[:12]
 nav=''.join(f'<a href="{depth}{url}" '+('aria-current="page"' if label==active else '')+f'>{label}</a>' for label,url in [('Research','index.html#research'),('Publications','publications.html'),('Experience','index.html#experience'),('Projects','index.html#projects'),('CV','cv.html')])
 nav+='<a href="https://scholar.google.com/citations?user=eGQ_BnwAAAAJ&amp;hl=en">Scholar</a>'
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(page_title)}</title><meta name="description" content="Raoof Zare Moayedi — machine learning research in privacy, robustness, and scientific learning."><meta name="theme-color" content="#0b0e14"><link rel="icon" type="image/svg+xml" href="{depth}assets/monogram.svg?v={mark_version}"><script>document.documentElement.dataset.palette='midnight';try{{const t=localStorage.getItem('theme');document.documentElement.dataset.theme=['light','dark'].includes(t)?t:'dark';localStorage.removeItem('palette')}}catch(e){{document.documentElement.dataset.theme='dark'}}</script><link rel="stylesheet" href="{depth}assets/site.css"><link rel="stylesheet" href="{depth}assets/redesign.css?v={style_version}"><script src="{depth}assets/site.js?v={script_version}" defer></script></head><body><a class="skip" href="#main">Skip to content</a><div class="progress" aria-hidden="true"></div><header class="header"><nav class="nav wrap" aria-label="Main navigation"><a class="brand" href="{depth}index.html"><span class="monogram" aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" aria-hidden="true"><rect class="mark-tile" width="64" height="64" rx="20"/><g transform="translate(-1 -2)"><path class="mark-letter" d="M19 46.5V24.5a4.75 4.75 0 0 1 9.5 0v.1c2.5-4.2 6.3-6.4 10.9-6.4h3.1a4.4 4.4 0 0 1 0 8.8h-3.1c-6.3 0-10.9 4.7-10.9 11v8.5a4.75 4.75 0 0 1-9.5 0Z"/><circle class="mark-point" cx="43" cy="46.5" r="4.75"/></g></svg></span><span class="brand-name"><strong>Raoof</strong><span>Zare Moayedi</span></span></a><div class="nav-right"><button class="menu-button" aria-label="Toggle navigation" aria-expanded="false" aria-controls="navigation">Menu</button><div class="nav-links" id="navigation">{nav}</div><details class="appearance-picker"><summary aria-label="Display options"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18Zm0 2v14a7 7 0 0 1 0-14Z"/></svg><span>Display</span></summary><div class="appearance-panel"><p class="appearance-title">Midnight</p><button type="button" class="theme-button" aria-label="Switch to light theme"><span aria-hidden="true">◐</span><span data-theme-label>Switch to light mode</span></button><button type="button" class="pointer-option" aria-pressed="false"><span class="pointer-option-icon" aria-hidden="true">✧</span><span>Playful pointer</span><span class="pointer-option-state" data-pointer-state>Off</span></button></div></details></div></nav></header><main id="main" class="wrap">{body}</main><footer class="footer"><div class="wrap"><a href="{depth}index.html">Raoof Zare Moayedi</a><a href="#main">Back to top</a></div></footer><div class="toast" role="status" aria-live="polite"></div></body></html>'''
hero_interests=[
 ('privacy','Privacy','privacy-sketch.webp','A little researcher studies protected data and similarly shaped synthetic points.','I study what can be learned under differential privacy and how much data it takes. My work connects algorithms with lower bounds to understand the trade-off between privacy and accuracy.'),
 ('unlearning','Unlearning','unlearning-robot-aligned.webp','A little robot erases one selected memory card while preserving the other connected memories.','I’m interested in how a model can forget selected training data without starting over. The challenge is to remove that data’s influence while preserving what the model learned from the rest.'),
 ('robustness','Adversarial Robustness','robustness-noisy-view.webp','A robot recognizes a cat through a view altered by mischievous pixel noise.','My work looks at adversarial attacks and misleading correlations. I study how robustness transfers between models, and how data and training choices affect it.'),
 ('robust-statistics','Robust Statistics','robust-statistics-aligned.webp','A little robot marks the center of a cluster of observations while a distant outlier tugs at it.','I’m interested in estimation when data contain outliers, heavy tails, or corruption. Which guarantees can we retain when standard statistical assumptions fail?'),
 ('uncertainty','Uncertainty quantification','uncertainty-aligned.webp','A robot predicts a moving ball with a central trajectory and a widening fan of possible future positions.','A prediction should come with some indication of how uncertain it is. I’m interested in whether a model’s confidence is justified, and how that uncertainty changes on unfamiliar data.'),
 ('training-dynamics','Training dynamics','sgd-noisy-steps.webp','A robot consults a handful of sample cards while taking uneven downhill steps across a small loss landscape.','I study how SGD and batch size shape what a model learns. Our work examines when implicit regularization helps models resist spurious correlations, and why early training matters.'),
 ('llm-reasoning','LLM reasoning','llm-reasoning-paths.webp','A thoughtful robot checks branching speech-bubble notes, rejects one reasoning path, and verifies another.','I’m interested in how language models solve problems over several steps, where their reasoning breaks down, and how to check whether an answer follows from the steps that produced it.'),
 ('scientific-learning','Scientific deep learning','scientific-learning-aligned.webp','A scientist robot connects a neural network to a fluid-flow experiment around a cylinder.','My work includes physics-informed neural networks for differential equations and graph neural networks for fluid dynamics. I’m interested in how physical structure can improve both the accuracy and cost of these models.')
]
hero_images=''.join(f'<img class="hero-sketch sketch-scene" data-sketch="{key}" src="assets/{asset}" alt="{esc(alt)}" width="1200" height="800" decoding="async"'+(' hidden' if i else '')+'>' for i,(key,label,asset,alt,description) in enumerate(hero_interests))
compact_labels={'scientific-learning':'Scientific ML'}
hero_buttons=''.join(f'<button type="button" class="interest-topic" data-landscape="{key}" data-description="{esc(description)}" data-label="{esc(label)}" aria-label="{esc(label)}" title="{esc(label)}" aria-pressed="{str(i==0).lower()}" aria-controls="interest-illustrations interest-title art-description">{esc(compact_labels.get(key,label))}</button>' for i,(key,label,asset,alt,description) in enumerate(hero_interests))
hero=f'''<section class="hero" id="about"><div class="hero-copy"><h1>Raoof<br>Zare Moayedi</h1><p class="hero-affiliation">M.Sc. Computer Science <span>Sharif University of Technology</span></p><p class="hero-lead">Fundamental questions<br><em>in machine learning</em></p><p class="hero-description">I’m a master’s student in Computer Science at Sharif University of Technology. I previously completed two bachelor’s degrees at Tehran Polytechnic: one in Computer Science and one in Mathematics. I’m curious about fundamental problems in machine learning, from the guarantees we can prove to the behavior we see in experiments. I like following the connections between problems, and my interests often extend beyond the topics of my current papers.</p><div class="hero-actions"><a class="button primary scholar-link" href="https://scholar.google.com/citations?user=eGQ_BnwAAAAJ&amp;hl=en">Google Scholar <span aria-hidden="true">↗</span></a><a class="button secondary" href="#research">View my research</a></div></div><div class="research-art sketch-panel interest-gallery" id="interests" role="region" aria-labelledby="interests-heading"><div class="interest-header"><div><h2 id="interests-heading">Research interests</h2><p class="interest-hint">Choose a topic to explore</p></div><span id="interest-count" aria-hidden="true">01 / 08</span></div><div class="interest-topics" role="group" aria-label="Choose a research interest">{hero_buttons}</div><div class="interest-stage"><div class="sketch-paper" id="interest-illustrations">{hero_images}</div></div><div class="interest-caption"><h2 id="interest-title">{hero_interests[0][1]}</h2><p id="art-description">{hero_interests[0][4]}</p><p class="sr-only" id="interest-status" role="status" aria-live="polite" aria-atomic="true"></p></div></div></section>'''
pub_by_id={p['id']:p for p in pubs}
selected=[pub_by_id[key] for key in ['Junhao_raoof', 'raoofzareCU', 'raoof_synthetic', 'raoof_private_sampling', 'raoof_private_splt', 'raoof_spurious']]
topics=['Adversarial robustness', 'Scientific ML', 'Differential privacy', 'Private sampling', 'Covariance estimation', 'SGD & robustness']
summaries=['Inverse adversarial examples help a smaller student learn a teacher’s robustness.', 'Penalizing residual curvature to improve how neural networks solve differential equations.', 'Private synthetic data with error guarantees that adapt to intrinsic geometry.', 'How much data do we need to privately generate a batch of Gaussian samples?', 'Private covariance estimation when different parties hold different features.', 'Why small batches early in training can reduce reliance on spurious correlations.']
artworks=['teacher-student-robots.webp', 'pinn-robot-aligned.webp', 'privacy-sketch.webp', 'private-sampling-robot-aligned.webp', 'private-covariance-robot-aligned.webp', 'sgd-noisy-steps.webp']
alts=['A larger robot guides a smaller student through a noisy example in their sketchbooks.', 'A robot examines residual curvature beside a neural network connected to a physical wave model.', 'A curious little researcher examines protected data and similar synthetic points.', 'A robot collects a fresh batch of samples from a bell-shaped machine with protected input records.', 'Two robots keep their feature tables in locked folders while a third assembles a shared covariance estimate.', 'A robot takes uneven downhill steps toward the bottom of a loss landscape, guided by a small handful of data cards.']
venues=['IEEE TPAMI', 'CMAME', 'PREPRINT', 'PREPRINT', 'PREPRINT', 'UNDER REVIEW']
cards=''
for i,p in enumerate(selected):
 venue_markup='<strong class="venue-highlight">IEEE TPAMI</strong>' if p['id']=='Junhao_raoof' else esc(venues[i])
 cards+=f'''<article class="work-card paper-card reveal" data-sketch-open="false"><div class="paper-body"><div class="card-meta"><span>{topics[i]}</span><span class="card-index">0{i+1}</span></div><h3><a class="paper-title" href="{p['project']}">{esc(p['title'])}</a></h3><div class="paper-preview"><p class="paper-summary">{summaries[i]}</p><div class="paper-art-reveal" aria-hidden="true"><div class="paper-art-clip"><figure class="paper-art"><img src="assets/{artworks[i]}" alt="{alts[i]}" width="1536" height="1024" loading="lazy" decoding="async"></figure></div></div></div><div class="paper-footer"><p class="card-venue">{p['year']} · {venue_markup}</p><span class="paper-arrow" aria-hidden="true">↗</span></div></div></article>'''
research=f'<section class="section publications-section" id="research"><div class="section-heading reveal"><div><p class="eyebrow">01 / Research</p><h2>Publications &amp; preprints</h2></div><a class="text-link" href="publications.html">All 7 publications</a></div><div class="work-grid">{cards}</div></section>'
exp=re.search(r'<div class="experience-list">(.*?)</div></section>',base,re.S).group(1)
rows=re.findall(r'<article class="institution-row">(.*?)</article>',exp,re.S)
experience='<section class="section experience-section" id="experience"><div class="section-heading reveal"><div><p class="eyebrow">02 / Experience</p><h2>Research experience</h2></div></div><div class="timeline">'
university_assets=['epfl.webp','cambridge.webp','ntu.svg','imperial.png']
def university_emblem(asset,name):
 return f'<span class="university-emblem"><img src="assets/universities/{asset}" alt="{esc(name)} logo" width="160" height="100" loading="lazy" decoding="async"></span>'
for i,row in enumerate(rows):
 h=re.search(r'<h3>(.*?)</h3>',row).group(1);role=re.search(r'<p class="position-role">(.*?)</p>',row).group(1);date=re.search(r'<p class="position-date">(.*?)</p>',row).group(1);desc=re.search(r'<div class="institution-description">(.*)</div>',row,re.S).group(1)
 experience+=f'<details class="journey reveal"><summary><span class="journey-date">{date}</span><span class="journey-name">{h}<small>{role}</small></span>{university_emblem(university_assets[i],h)}<span class="expand" aria-hidden="true">+</span></summary><div class="journey-description">{desc}</div></details>'
experience+='</div></section>'
education=f'''<section id="education" class="section"><div class="section-heading"><div><p class="eyebrow">03 / Education</p><h2>Education</h2></div><a class="text-link" href="cv.html">Full CV</a></div><div class="education-list">
<article class="education-row"><div class="education-copy"><div class="education-heading"><h3>Sharif University of Technology</h3>{university_emblem('sharif.webp','Sharif University of Technology')}</div><div class="degree-record"><p class="degree-name">M.Sc. in Computer Science</p><p class="position-date">2024 – present</p><p class="degree-thesis"><span>Master’s thesis</span><a href="research/private-sampling.html">Minimax-Optimal Private Multi-Sampling from Gaussian Distributions</a></p><dl class="academic-record"><div><dt>GPA</dt><dd>19.71<span> / 20</span></dd></div><div><dt>Class rank</dt><dd>1st<span> · ongoing</span></dd></div></dl></div></div></article>
<article class="education-row"><div class="education-copy"><div class="education-heading"><h3>Amirkabir University of Technology (Tehran Polytechnic)</h3>{university_emblem('amirkabir.png','Amirkabir University of Technology')}</div><div class="degree-record"><p class="degree-name">B.Sc. in Computer Science</p><p class="position-date">2018 – 2023</p><p class="degree-thesis"><span>Bachelor’s thesis</span>A Survey on Differentially Private Algorithms</p><dl class="academic-record"><div><dt>GPA</dt><dd>18.82<span> / 20</span></dd></div><div><dt>Graduating class rank</dt><dd>3rd</dd></div></dl></div><div class="degree-record"><p class="degree-name">B.Sc. in Mathematics</p><p class="position-date">2019 – 2023</p><dl class="academic-record"><div><dt>GPA</dt><dd>18.99<span> / 20</span></dd></div><div><dt>Graduating class rank</dt><dd>2nd</dd></div></dl></div></div></article></div></section>'''
# Projects are intentionally text-only: titles and broad topic labels.
project_items=[
 ('Model geometry','Input-Space Geometry of CNNs and Transformers'),
 ('Data selection','Robust Data Pruning'),
 ('Sampling','A New Coupling for Sampling from Compact Convex Bodies'),
 ('Audio models','Task Arithmetic for Audio Foundation Models'),
 ('Vision & language','Robust Prompt Tuning for Vision–Language Models')
]
project_routes={'Input-Space Geometry of CNNs and Transformers':'projects/input-space-geometry.html','Robust Data Pruning':'projects/robust-data-pruning.html','Task Arithmetic for Audio Foundation Models':'projects/audio-task-arithmetic.html','A New Coupling for Sampling from Compact Convex Bodies':'projects/convex-body-coupling.html','Robust Prompt Tuning for Vision–Language Models':'projects/robust-prompt-tuning.html'}
project_entries=''
for i,(topic,title) in enumerate(project_items,1):
 project_title=f'<a class="project-title-link" href="{project_routes[title]}">{esc(title)}<span class="project-link-arrow" aria-hidden="true"> ↗</span></a>' if title in project_routes else esc(title)
 project_entries+=f'<li class="project-entry"><span class="project-number" aria-hidden="true">{i:02d}</span><div><p class="project-topic">{esc(topic)}</p><h3>{project_title}</h3></div></li>'
projects=f'<section class="section projects-section" id="projects" aria-labelledby="projects-title"><div class="section-heading"><div><p class="eyebrow">04 / Projects</p><h2 id="projects-title">Projects</h2></div></div><ol class="project-list" role="list">{project_entries}</ol></section>'
# Academic coursework and teaching, transcribed from the supplied CV.
grad_courses=[('Generative Models','20'),('Learning Theory','20'),('Advanced Statistics','20'),('Information Theory','20'),('Bandit Learning','20'),('Measure Theory and Probability','20'),('Advanced Algorithms','18.2'),('Functional Analysis','17')]
undergrad_courses=[('Computer Graphics','20'),('Game Theory','20'),('Stochastic Process','20'),('Combinatorial Optimization','20')]
grad_teaching=[('Learning Theory','Fall 2025'),('Information Theory','Fall 2024'),('Trustworthy Machine Learning','Fall 2024'),('Scientific Deep Learning','Fall 2024'),('Measure Theory and Probability','Fall 2022'),('Machine Learning','Fall 2022')]
undergrad_teaching=[('Real Analysis','Spring 2023'),('Applied Linear Algebra','Fall 2022'),('Stochastic Process','Spring 2022'),('Computational Theory','Fall 2021')]
def academic_rows(records,grades=False):
 return '<ul class="course-list">'+''.join(f'<li><span>{esc(name)}</span><span class="course-detail">{esc(detail)}'+('<span class="sr-only"> out of 20</span>' if grades else '')+'</span></li>' for name,detail in records)+'</ul>'
coursework=f'''<section class="section" id="coursework" aria-labelledby="coursework-title"><div class="section-heading"><div><p class="eyebrow">06 / Coursework</p><h2 id="coursework-title">Relevant coursework</h2></div><p class="section-aside">All grades out of 20</p></div><div class="academic-grid coursework-grid"><article class="academic-panel"><div class="academic-panel-heading"><h3>Graduate courses</h3></div>{academic_rows(grad_courses,True)}</article><article class="academic-panel"><div class="academic-panel-heading"><h3>Undergraduate courses</h3></div>{academic_rows(undergrad_courses,True)}</article></div><div class="audited-courses"><h3>Audited courses <span>Graduate level</span></h3><ul><li>High-Dimensional Statistics</li><li>Convex Optimization</li><li>Discrete Differential Geometry</li><li>Introduction to Matroids</li><li>High-Dimensional Robust Statistics</li><li>Large Language Models</li></ul></div></section>'''
teaching=f'''<section class="section" id="teaching" aria-labelledby="teaching-title"><div class="section-heading"><div><p class="eyebrow">05 / Teaching</p><h2 id="teaching-title">Teaching Assistant</h2></div><a class="text-link" href="cv.html">Full CV</a></div><div class="academic-grid"><article class="academic-panel"><div class="academic-panel-heading"><h3>Graduate courses</h3></div>{academic_rows(grad_teaching)}</article><article class="academic-panel"><div class="academic-panel-heading"><h3>Undergraduate courses</h3></div>{academic_rows(undergrad_teaching)}</article></div></section>'''
contact='''<section class="contact-panel reveal" id="contact"><p class="eyebrow">Contact</p><h2>Get in touch</h2><div class="contact-actions"><a class="button primary" href="mailto:Raoofmoayedi2000@gmail.com">Email me</a><a class="button secondary" href="https://scholar.google.com/citations?user=eGQ_BnwAAAAJ&amp;hl=en">Google Scholar</a></div><a class="email-address" href="mailto:Raoofmoayedi2000@gmail.com">Raoofmoayedi2000@gmail.com</a></section>'''
(out/'index.html').write_text(shell('',hero+research+experience+education+projects+teaching+coursework+contact))
# Keep the complete academic record and research explanations.
for path in [Path('cv.html'),*Path('content/research').glob('*.html')]:
 rel=path if path.name=='cv.html' else Path('research')/path.name
 raw=(src/rel).read_text();body=re.search(r'<main[^>]*>(.*)</main>',raw,re.S).group(1);title=re.search('<title>(.*?)</title>',raw).group(1).split(' | ')[0]
 (out/rel).write_text(shell(title,body,'../' if rel.parent.name=='research' else '', 'CV' if rel.name=='cv.html' else 'Research'))
# Project pages share the same layout and navigation as the research pages.
(out/'projects').mkdir(exist_ok=True)
for path in (src/'projects').glob('*.html'):
 raw=path.read_text();body=re.search(r'<main[^>]*>(.*)</main>',raw,re.S).group(1);title=re.search('<title>(.*?)</title>',raw).group(1).split(' | ')[0]
 (out/'projects'/path.name).write_text(shell(title,body,'../','Projects'))
# Publication cards stay fully readable without JavaScript.
body='''<header class="page-hero"><p class="eyebrow">Papers &amp; preprints</p><h1>Publications</h1><p>My work on differential privacy, robust learning, and scientific machine learning.</p></header><section class="publication-page"><div class="publication-tools"><label class="search-field"><span class="sr-only">Search publications</span><input id="paper-search" type="search" placeholder="Search by title, author, or topic…"></label><a class="text-link" href="papers.bib" download>Download BibTeX</a></div><div class="filter-row"><div class="filters" role="group" aria-label="Filter publications"><button class="filter" data-filter="all" aria-pressed="true">All work <span>7</span></button><button class="filter" data-filter="privacy" aria-pressed="false">Privacy</button><button class="filter" data-filter="robustness" aria-pressed="false">Robustness</button><button class="filter" data-filter="scientific" aria-pressed="false">Scientific ML</button></div><span id="result-count" role="status">7 publications</span></div><div id="paper-list">'''
bib=(src/'papers.bib').read_text(); entries=re.split(r'\n\n',bib.strip())
bib_by_id={re.search(r'@\w+\{([^,]+),',entry).group(1):entry for entry in entries}
for i,p in enumerate(pubs):
 topic='privacy' if p['id'] in ['raoof_synthetic','raoof_private_splt','raoof_private_sampling'] else 'scientific' if p['id']=='raoofzareCU' else 'robustness'
 title=esc(p['title']);link=p.get('project',p.get('url',''))
 publication_venue='<strong class="venue-highlight">IEEE TPAMI</strong> · '+esc(p['venue']) if p['id']=='Junhao_raoof' else esc(p['venue'])
 actions=(f'<a href="{p["url"]}" target="_blank" rel="noopener">Read paper</a>' if p.get('url') else '')+(f'<a href="{p["project"]}">Research details</a>' if p.get('project') else '')
 body+=f'''<article class="pub library-paper" data-topic="{topic}"><div class="pub-label"><span class="pub-year">{p['year']}</span><span class="card-index">0{i+1}</span></div><div class="pub-content"><p class="paper-status">{esc(p['status'])} · {topic.title()}</p><h3><a href="{link}">{title}</a></h3><p class="pub-authors">{esc(', '.join(p['authors'])).replace('R. Zare Moayedi','<strong>R. Zare Moayedi</strong>')}</p><p class="pub-meta">{publication_venue}</p><div class="pub-actions">{actions}<details><summary>BibTeX</summary><pre>{esc(bib_by_id[p['id']])}</pre><button class="copy-citation">Copy citation</button></details></div></div></article>'''
body+='</div><div id="empty-state" hidden><h2>No matching publications</h2><p>Try a different keyword or research topic.</p><button class="button secondary" id="reset-search">Clear filters</button></div><p class="pub-footer">* Equal contribution. Statuses last updated in September 2026.</p></section>'
(out/'publications.html').write_text(shell('Publications',body,active='Publications'))
(out/'papers.bib').write_text('\n\n'.join(bib_by_id[p['id']] for p in pubs)+'\n');shutil.copy(src/'assets/site.css',out/'assets/site.css')
(out/'404.html').write_text(shell('Page not found','<div class="page-hero"><p class="eyebrow">404</p><h1>Page not found</h1><p>The link may be out of date.</p><a class="button primary" href="/index.html">Back to research</a></div>'))
print('Generated public pages and bibliography.')
